### ISSUE TITLE
Will there be a new version of NPPS, Sif_Win32?

### ISSUE THREAD

**Issue by OumasTrashForever** [DarkEnergyProcessor/NPPS#2]
At least up to 4.x.x. I installed Sif_Win32 and NPPS on it, and now I’m wondering if it will be updated at all after two years, or is it officially a dead project?

**Comment by MikuAuahDark** [comment]
It's dead now. I don't maintain SIF-Win32 nor even this one.

Pada tanggal Sab, 17 Nov 2018 22.51, OumasTrashForever <
notifications@github.com> menulis:

**Comment by vincent38** [comment]
Rip NPPS. Is there a private project we can ask access, or has everybody
gave up on this kind of stuff ?

**Comment by MikuAuahDark** [comment]
Given how fast and rapid is SIF development are, I don't think anybody will have time to create private server. The development is so fast that people can't keep up with breaking changes that SIF mostly introduced.

**Comment by kotori2** [comment]
It is too hard to keep SIF-WIN32 to work with latest SIF lua.🙃 But for private server, I have one but it is closed source.

**Comment by vincent38** [comment]
Okay too bad. Thanks for replying
